### ISSUE TITLE
Add commit lint husky hook for Conventional Commits

### ISSUE THREAD

**Issue by somratAtSekaiLab** [monstar-lab-oss/admin-panel-template-reactjs#130]
### Discussed in https://github.com/monstar-lab-oss/admin-panel-template-reactjs/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **somratAtSekaiLab** November 30, 2021</sup>
Commit messages should follow the [Conventional Commits](https://www.conventionalcommits.org/) rule followed by [Commit lint config conventional](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional)

Useful links: 
https://github.com/conventional-changelog/commitlint</div>

**Comment by jacksonjp** [comment]
Closed in favour of github actions like mergeable, and we squash and merge PR's
