### ISSUE TITLE
Table (example)

### ISSUE THREAD

**Issue by themitvp** [monstar-lab-oss/admin-panel-template-reactjs#20]
- [x] Table
- [x] Fetch data
- [x] Pagination
- [x] Filtering
- [x] Ordering
- [x] Searching
- [x] All params in URL (for example `"/users?orderBy=name-asc"`)
- [x] Select row (bulk actions)
- [x] Row actions (Edit, Delete)

**Comment by yukinoda** [comment]
Related material UI component: https://material-ui.com/components/tables/

**Comment by yukinoda** [comment]
Filtering is not implemented yet in Material-UI
https://material-ui.com/components/data-grid/filtering/

**Comment by yukinoda** [comment]
Current demo under development
https://material-table.com/#/docs/features/filtering

**Comment by yukinoda** [comment]
Filter Design Reference
https://material-table.com/#/docs/features/filtering

**Comment by yukinoda** [comment]
Taking reference to this component
https://github.com/gregnb/mui-datatables#usage

**Comment by yukinoda** [comment]
https://reqres.in/api/USERS
&
https://reqres.in/api/users

have different response

**Comment by yukinoda** [comment]
@themitvp cc: @danfirestone 
Maybe we should leave this issue opened even after this PR is merged https://github.com/monstar-lab-oss/admin-panel-template-reactjs/pull/52

**Comment by yukinoda** [comment]
- [ ]  Filtering
- [ ]  Ordering
- [ ]  Searching
- [ ]  All params in URL (for example "/users?orderBy=name-asc")
- [ ]  Row actions (Edit, Delete)

Are left
