### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by themitvp** [monstar-lab-oss/admin-panel-template-reactjs#7]
- [x] How to change color scheme (docs/theming.md)
- [x] How to style material ui components?
- [x] How to change color palette?
- [x] How to change spacings?
- [x] How to have multiple themes?
- [x] Light theme vs Dark theme?
- [x] Themes based on user role?

**Comment by yukinoda** [comment]
@themitvp
should the file name be docs/theming.md?

**Comment by themitvp** [comment]
hmm good question 🤔  yeah I think that might be better as it might be a bit confusing that you find it under `styles`

**Comment by yukinoda** [comment]
is now in `src/docs/theming.md`
